version: 2

jobs:

 build:
   docker:
    - image: cimg/node:current

   steps:
    - checkout
    - setup_remote_docker

    - run:
       name: build client
       command: docker build -t intelligentwater/iwp:client -f ./client/Dockerfile .

    - run:
       name: build server
       command: docker build -t intelligentwater/iwp:server -f ./server/Dockerfile .

    - run:
       name: push client
       command: |
         docker login -u intelligentwater -p 1717intelligent-docker!
         docker push intelligentwater/iwp:client
    - run:
       name: push server
       command: |
         docker login -u intelligentwater -p 1717intelligent-docker!
         docker push intelligentwater/iwp:server
   
   deploy-dev:
      machine: true
      steps:
        - checkout

        - run:
            name: Build and push Docker image to Heroku
            command: |
              sudo curl https://cli-assets.heroku.com/install.sh | sh
              HEROKU_API_KEY=$d5d8189d-826c-4111-aa1d-5f1cde57fc5a heroku container:login
              HEROKU_API_KEY=$d5d8189d-826c-4111-aa1d-5f1cde57fc5a heroku container:push web
              HEROKU_API_KEY=$d5d8189d-826c-4111-aa1d-5f1cde57fc5a heroku container:release web
